name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Build WebView APK
        uses: noobdev/html-apk-builder@v2
        with:
          # 你的APP基础信息
          appName: "电子通行证"
          packageId: "com.police.pass"
          versionCode: 2
          versionName: "1.1"
          appIcon: "icon.png"
          
          # 100% 你所有的UI定制需求
          fullScreenBackground: true
          statusBarColor: "#00000000"
          statusBarDarkIcons: true
          screenOrientation: "portrait"
          
          # 根治你所有BUG的核心配置
          disableWebViewCache: true
          disableNetworkAccess: true
          localFileOnly: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: output/app-release.apk
