name: Build Android APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout All Files
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Build Tool
        run: pip install html2apk==1.2.0

      - name: Execute APK Build
        run: html2apk build --app-name "电子通行证" --package-id "com.police.pass" --version-code 2 --version-name "1.1" --icon "./icon.png" --background "./bg.jpg" --status-bar-color "#00000000" --status-bar-dark-icon true --full-screen true --screen-orientation "portrait" --disable-cache true --local-only true --block-all-network true

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: output/app-release.apk
